### ISSUE TITLE
psql, mysql & mongo

### ISSUE THREAD

**Issue by mipearson** [campjs/NaN#4]

**Comment by eugeneware** [comment]
probably a redis too for good measure :-)

**Comment by eugeneware** [comment]
no mongo?

On Wed, May 21, 2014 at 9:34 PM, mipearson notifications@github.com wrote:

> Closed #4 https://github.com/campjs/NaN/issues/4 via 7a59e50https://github.com/campjs/NaN/commit/7a59e508079b373a23eb5f123cd6535b2bce9e9b
> .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/campjs/NaN/issues/4#event-123305166
> .

## 

_Eugene Ware_
Chief Executive Officer

Phone: +61 3 9955 7041
Email: eugene@noblesamurai.com
Twitter: @EugeneWare http://twitter.com/EugeneWare

_Noble Samurai Pty Ltd_
Level 1, 234 Whitehorse Rd
Nunawading, Victoria, 3131, Australia

noblesamurai.com http://www.noblesamurai.com/ | eugeneware.com |
facebook.com/Eugene.S.Ware http://www.facebook.com/Eugene.S.Ware

**Comment by mipearson** [comment]
Mongo was already there :)

On Wed, May 21, 2014 at 10:49 PM, Eugene Ware notifications@github.comwrote:

> no mongo?
> 
> On Wed, May 21, 2014 at 9:34 PM, mipearson notifications@github.com
> wrote:
> 
> > Closed #4 https://github.com/campjs/NaN/issues/4 via 7a59e50<
> > https://github.com/campjs/NaN/commit/7a59e508079b373a23eb5f123cd6535b2bce9e9b>
> > 
> > .
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/campjs/NaN/issues/4#event-123305166>
> > .
> 
> ## 
> 
> _Eugene Ware_
> Chief Executive Officer
> 
> Phone: +61 3 9955 7041
> Email: eugene@noblesamurai.com
> Twitter: @EugeneWare http://twitter.com/EugeneWare
> 
> _Noble Samurai Pty Ltd_
> Level 1, 234 Whitehorse Rd
> Nunawading, Victoria, 3131, Australia
> 
> noblesamurai.com http://www.noblesamurai.com/ | eugeneware.com |
> facebook.com/Eugene.S.Ware http://www.facebook.com/Eugene.S.Ware
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/campjs/NaN/issues/4#issuecomment-43749483
> .

## 

Michael Pearson

**Comment by rvagg** [comment]
@mipearson can you rsync npm again? I had a dismal time getting it downloaded but it's all there on the server if you have time. ~111G

**Comment by rvagg** [comment]
Sorry for commenting here, on my phone and 1/2 asleep

**Comment by mipearson** [comment]
I just stopped / started it this morning, expecting that would be the case
:)

78gb down so far.

On Thu, May 22, 2014 at 7:44 AM, Rod Vagg notifications@github.com wrote:

> Sorry for commenting here, on my phone and 1/2 asleep
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/campjs/NaN/issues/4#issuecomment-43818249
> .

## 

Michael Pearson
