### ISSUE TITLE
Nodebots related stuff

### ISSUE THREAD

**Issue by ajfisher** [campjs/NaN#8]
We'll need installers for johnny-five, node serialport and node firmata. That should be all we need npm wise.

Installers wise we'll need installers for Arduino IDE for Mac, Linux, Windows and ideally MS Visual Studio Express for windows due to the compilation step for serialport on windows :(

I'm assuming  Xcode / Command Line Tools so we can get node built for mac?

**Comment by mipearson** [comment]
Are you able to get me links for those?

I'll be setting up a general access read-only share for this sort of thing.
I'll download it at work tomorrow (my home internet is worse than CampJS')
and make sure it's on NaN.

On Tue, May 20, 2014 at 5:57 PM, ajfisher notifications@github.com wrote:

> We'll need installers for johnny-five, node serialport and node firmata.
> That should be all we need npm wise.
> 
> Installers wise we'll need installers for Arduino IDE for Mac, Linux,
> Windows and ideally MS Visual Studio Express for windows due to the
> compilation step for serialport on windows :(
> 
> I'm assuming Xcode / Command Line Tools so we can get node built for mac?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/campjs/NaN/issues/8
> .

## 

Michael Pearson

**Comment by ajfisher** [comment]
Okay:

Arduino: http://arduino.cc/en/Main/Software
Win: http://arduino.googlecode.com/files/arduino-1.0.5-r2-windows.exe
Mac: http://arduino.googlecode.com/files/arduino-1.0.5-macosx.zip
Linux (32bit: http://arduino.googlecode.com/files/arduino-1.0.5-linux32.tgz) (64 bit: http://arduino.googlecode.com/files/arduino-1.0.5-linux64.tgz)

Xcode, don't worry about as we can just give peeps a running folder.

The npms are johnny-five, serialport, firmata + all deps.

And I'll try and track down a Windows installer for VS Express.

**Comment by SomeoneWeird** [comment]
There's an offline iso you can download for VS (at least for 2010 there
was). It took a bit if finding on their website though

**Comment by SomeoneWeird** [comment]
http://go.microsoft.com/fwlink/?LinkId=255978

looks like you can use this to download the iso...

**Comment by ajfisher** [comment]
Stellar - thanks for sourcing that @SomeoneWeird much appreciated.

I think with all of that plus versions of node etc floating about I reckon we'll be good to go.

**Comment by mipearson** [comment]
I've set all of these to download overnight - they'll be on a shared drive at camp.
