### ISSUE TITLE
APT Mirror

### ISSUE THREAD

**Issue by SomeoneWeird** [campjs/NaN#9]
Not sure what infra is needed, probably just some fancy nginx config, I have copies of trusty and raring, looking at saucy & precise but they're both ~60gb - will have to see how time goes. Trusty & Raring = ~60gb together.

**Comment by eugeneware** [comment]
I've got a trusty copy, and also currently doing quantal (what dokku is
based on). If I get some more time I might also have a crack at precise for
good measure.

On Wed, May 21, 2014 at 10:16 AM, Adam Brady notifications@github.comwrote:

> Not sure what infra is needed, probably just some fancy nginx config, I
> have copies of trusty and raring, looking at saucy & precise but they're
> both ~60gb - will have to see how time goes. Trusty & Raring = ~60gb
> together.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/campjs/NaN/issues/9
> .

## 

_Eugene Ware_
Chief Executive Officer

Phone: +61 3 9955 7041
Email: eugene@noblesamurai.com
Twitter: @EugeneWare http://twitter.com/EugeneWare

_Noble Samurai Pty Ltd_
Level 1, 234 Whitehorse Rd
Nunawading, Victoria, 3131, Australia

noblesamurai.com http://www.noblesamurai.com/ | eugeneware.com |
facebook.com/Eugene.S.Ware http://www.facebook.com/Eugene.S.Ware

**Comment by SomeoneWeird** [comment]
@eugeneware awesome, will leave saucy downloading overnight, and if you manage to pull precise we'll have 12.10 -> 14.04, should cover everyone running ubuntu :+1:

**Comment by eugeneware** [comment]
Awesome. Sounds like a plan!

On Wed, May 21, 2014 at 3:40 PM, Adam Brady notifications@github.comwrote:

> @eugeneware https://github.com/eugeneware awesome, will leave saucy
> downloading overnight, and if you manage to pull precise we'll have 12.10
> -> 14.04, should cover everyone running ubuntu [image: :+1:]
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/campjs/NaN/issues/9#issuecomment-43714189
> .

## 

_Eugene Ware_
Chief Executive Officer

Phone: +61 3 9955 7041
Email: eugene@noblesamurai.com
Twitter: @EugeneWare http://twitter.com/EugeneWare

_Noble Samurai Pty Ltd_
Level 1, 234 Whitehorse Rd
Nunawading, Victoria, 3131, Australia

noblesamurai.com http://www.noblesamurai.com/ | eugeneware.com |
facebook.com/Eugene.S.Ware http://www.facebook.com/Eugene.S.Ware
